07 virtual environments to iterate and test
Lumi-supercomputer/Getting_Started_with_AI_workshop pull request #4
Opened 2024-05-13 10:54 UTC by gregordecristoforo

2024-05-13 12:17 UTC, Chroxvi commented
A few things, you may want to consider:

- This venv approach may also be used with the LUMI application containers, e.g. `/appl/local/containers/sif-images/lumi-pytorch-rocm-5.6.1-python-3.10-pytorch-v2.2.2.sif`, which may be worth mentioning. It still requires activating the conda environment (`$WITH_CONDA`) before creating the venv. Also note that building a (final) container from e.g. `/appl/local/containers/sif-images/lumi-pytorch-rocm-5.6.1-python-3.10-pytorch-v2.2.2.sif` + a venv is not necessarily that easy - at least it is not directly supported by e.g. cotainr.
- I think, we should stress that you need to source the venv activate script every time you run the container to get access to the venv installed packages (after running `$WITH_CONDA` if using the LUMI application containers). And you need to keep track of which venv to activate with a given container for a given application/project (another reason to build a container with everything included, or, alternatively, use the EasyBuild integration to the LUMI Application containers to manage this).
- I also think, we should stress that the venv is installed on the Lustre files systems (not inside the container which is read-only) with all the small files / bad performance issues it may create.
- Torchvision is actually already installed in the `minimal_python.yml` conda env. It makes it slightly confusing to install the same package again in a venv. Maybe choose another package to install instead?
- The `singularity-userfilesystems` module is not (yet) available in the central LUMI stacks. You might want to mention that `module use /project/project_465001063/modules` is currently needed to have access to it.

2024-05-16 05:53 UTC, gregordecristoforo commented
Thank you @Chroxvi  for your comments, I incorporated them in the guide. (Sorry for mentioning the wrong package that is installed via pip, I intended to install `torchmetrics` instead of `torchvision` which was already correct in the `pip list` but not in the explicit `pip install`).
Are there any other issues/comments before it can be merged?

2024-05-23 12:19 UTC, Chroxvi commented
Since we no longer have a hands-on session for this lecture, I wonder if you rework this into a "minimal full example" and then keep the remarks and discussion in your slides? What do you think?

2024-05-24 13:25 UTC, gregordecristoforo commented
I turned the relatively detailed instructions into a "minimal full example". All the removed details are still included in the slides.

2024-05-27 08:46 UTC, Chroxvi requested changes
Generally looks good. The custom modules path needs to be updated. And maybe add a short description of how to run the container with the venv. See comments.

2024-05-27 08:46 UTC, Chroxvi commented on 07_Virtual_environments_to_iterate_and_test/README.md
> +module use /project/project_465001063/modules
```suggestion
module use /appl/local/training/modules/AI-20240529/
```

2024-05-27 08:46 UTC, Chroxvi commented on 07_Virtual_environments_to_iterate_and_test/README.md
> +
Maybe add a section showing how to correctly run the container with the venv, i.e. sourcing the venv.

2024-05-27 08:57 UTC, gregordecristoforo commented
Thanks for the comments, I included your suggestions.

2024-05-27 09:52 UTC, Chroxvi approved these changes
Ready for merge!

2024-05-27 09:52 UTC, merged